export const NotificationErrorCode = {
  INVALID_RECIPIENT: "INVALID_RECIPIENT",
  RATE_LIMITED: "RATE_LIMITED",
  TIMEOUT: "TIMEOUT",
  ABORTED: "ABORTED",
  CONFIG_ERROR: "CONFIG_ERROR",
  PROVIDER_AUTH_ERROR: "PROVIDER_AUTH_ERROR",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  TEMPLATE_RENDER_ERROR: "TEMPLATE_RENDER_ERROR",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  INVALID_MESSAGE: "INVALID_MESSAGE",
  CHANNEL_NOT_CONFIGURED: "CHANNEL_NOT_CONFIGURED",
} as const;

export const Channels = {
  SMS: "sms",
  EMAIL: "email",
  PUSH: "push",
} as const;
